### ISSUE TITLE
Broken link "Meet all learners"

### ISSUE THREAD

**Issue by mudrd8mz** [getsmarter/moodle-block_meet_the_students#9]
I live in impression I've reported this before but I may be wrong (btw there is no need to delete reported issues here, better to leave them archived as resolved).

The link "Meet all learners" does not work on sites that have Moodle installed in a sub-directory of the domain

    $this->content->footer = '<a href="/user/index.php?contextid='.$context->id.'">';

Better to use `html_writer::link()` that would deal with this for you.

**Comment by mikhailjan** [comment]
I'm not sure if there is an option to resolve an issue, I only see an option to close the issue. That's what I did before.
Anyway, I have fixed the link using `html_writer::link()` and `new moodle_url()` and will submit a new version just now.
